# Generated by Django 6.0.1 on 2026-01-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_timestamp_visitor_visited_at_visitor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
