# Generated by Django 6.0.1 on 2026-02-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
