"""
Django settings for meektech project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Read ALLOWED_HOSTS from environment and convert to a list (comma-separated).
# Default to common local hosts and strip any port components that may appear.
ALLOWED_HOSTS_ENV = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost")
_allowed = []
for raw in ALLOWED_HOSTS_ENV.split(","):
    host = raw.strip()
    if not host:
        continue
    # IPv6 with brackets may look like [::1]:8000 — keep bracketed address
    if host.startswith('[') and ']' in host:
        # remove trailing port if present: [::1]:8000 -> [::1]
        host = host.split(']')[0] + ']'
    elif ':' in host:
        # remove port from IPv4 or hostname: example 127.0.0.1:8000 -> 127.0.0.1
        host = host.split(':', 1)[0]
    if host and host not in _allowed:
        _allowed.append(host)
# Ensure common development hosts are present
for dev in ('127.0.0.1', 'localhost', '0.0.0.0', '::1'):
    if dev not in _allowed:
        _allowed.append(dev)
ALLOWED_HOSTS = _allowed

# Application definition

INSTALLED_APPS = [
    # AdminTheme
    "spectra",
    "django_user_agents",
    
    # Django core apps
    'django.contrib.admin',
    'meektech.auth_app.AuthConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # meektech apps
    "apps.core",
    # "accounts",
    # "client",
    # "staff",
    # "intern",
    # "portals.staff_portal",
    # "portals.intern_portal",
    "apps.about",
    "apps.blog",
    "apps.careers",
    "apps.projects",
    "apps.services",
    "apps.solutions",
    "apps.newsletter",

    # tailwind
    'tailwind',
    'theme',

    # newsletter editor
    'ckeditor',
    'ckeditor_uploader',

    # newsletter scheduller
    "django_apscheduler",

]

SITE_ID = 1

TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'spectra.middleware.SpectraThemeMiddleware',
    'apps.core.middleware.VisitorTrackingMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'meektech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'spectra.context_processors.spectra_context',
                'apps.core.context_processors.google_maps_key',
            ],
        },
    },
]


WSGI_APPLICATION = 'meektech.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv("DB_NAME"),
#         'USER': os.getenv("DB_USER"),
#         'PASSWORD': os.getenv("DB_PASSWORD"),
#         'HOST': os.getenv("DB_HOST"),
#         'PORT': os.getenv("DB_PORT"),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
# Set the default time zone to Lagos (WAT - West Africa Time)
TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
    # STATIC_ROOT = BASE_DIR / 'static'
    # STATICFILES_DIRS = []
# For production only (collectstatic will copy files here)
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Do not put your working static here
# Project-level static files (development)
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # This points to your project-level static folder
]


# Node.js and NPM paths for tailwind
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"


GEOIP_PATH = BASE_DIR / "geoip"  # folder where MaxMind database is stored

SPECTRA_CONFIG = {
    # ===== Branding =====
    "site_title": "My Awesome Site",
    "site_header": "My Admin Dashboard",
    "index_title": "DashboardT",
    "logo": "images/logo.png",  # Path to your logo in static files
    "favicon": "images/logo3.png",
    "logo_sm": "",
    "logo_dark": "",
    
    # ===== Theme Settings =====
    "theme": "light",  # Default theme: 'light' or 'dark'
    "enable_dark_mode": True,
    "enable_theme_toggle": True,
    
    "theme_colors": {
        "primary": "#6366f1",
        "primary_hover": "#4f46e5",
        "secondary": "#10b981",
        "secondary_hover": "#059669",
        "accent": "#f59e0b",
        "danger": "#ef4444",
        "success": "#10b981",
        "warning": "#f59e0b",
        "info": "#3b82f6",
    },

    # ===== Dashboard =====
    "show_app_list": True,
    "show_recent_actions": True,
    "recent_actions_limit": 10, # Show last 10 actions
    "show_add_button": True,
    "welcome_message": "Welcome back to your dashboard",
    "sidebar_show_user": True,
    "show_badges": True,
    "sidebar_menu_items": True,
    "show_notifications": True,
    
    # ===== Dashboard Widgets ====
    "dashboard_widgets": [
        {
            "widget": "spectra.dashboard.widgets.StatsWidget",
            "width": "w-full",
            "order": 1
        },
        {
            "widget": "spectra.dashboard.widgets.ActivityChartWidget",
            "width": "lg:w-2/3",
            "order": 2
        },
        {
            "widget": "spectra.dashboard.widgets.RecentActionsWidget",
            "width": "lg:w-1/3",
            "order": 3
        }
    ],
    
    # ===== Widget Settings =====
    "stats_refresh_interval": 300,  # seconds
    "chart_default_period": 30,  # Show last 30 days
    "enable_charts": True,
    
    # ===== Customization =====
    "custom_css": [
        "css/custom-admin.css",
    ],
    "custom_js": [
        "js/custom-admin.js",
    ],
    
    # ===== Advanced =====
    "enable_api": True,
    "cache_timeout": 300,
    "debug_mode": True,

    # ===== Footer =====
    "copyright": "All right reserved. Developed with ❤️ by Engr. Micheal Shokunbi"
}



MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# AUTH_USER_MODEL = "accounts.User"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes")

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = "Meek Technology <no-reply@meektechnology.com>"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Make sure to set the GOOGLE_MAPS_API_KEY in your environment variables
GOOGLE_MAPS_API_KEY = os.getenv("GOOGLE_MAPS_API_KEY")

# print("GOOGLE MAP KEY:", GOOGLE_MAPS_API_KEY)
# print("ALLOWED_HOSTS:", ALLOWED_HOSTS)

CKEDITOR_UPLOAD_PATH = 'ckeditor/'

# CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"

# CELERY_BROKER_URL = "filesystem://"

# CELERY_BROKER_TRANSPORT_OPTIONS = {
#     "data_folder_in": os.path.join(BASE_DIR, "celery", "in"),
#     "data_folder_out": os.path.join(BASE_DIR, "celery", "out"),
#     "data_folder_processed": os.path.join(BASE_DIR, "celery", "processed"),
# }
