# Generated by Django 6.0.1 on 2026-02-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettercampaign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='newsletterrecipient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newsletterrecipient',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='newsletterrecipient',
            name='status',
        ),
    ]
