# Generated by Django 6.0.1 on 2026-02-19 13:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_remove_newslettercampaign_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettercampaign',
            name='body_html',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
