# Generated by Django 6.0.1 on 2026-02-20 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_newslettercampaign_body_html'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterImage',
        ),
        migrations.AddField(
            model_name='newsletterrecipient',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletterrecipient',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='newsletter.newslettercampaign'),
        ),
    ]
