# Generated by Django 6.0.1 on 2026-02-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_newsletterimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterimage',
            name='image',
            field=models.ImageField(upload_to='media/newsletter_images/'),
        ),
    ]
