# Generated by Django 6.0.1 on 2026-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_alter_newsletterimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='send_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='target_subscribers',
            field=models.ManyToManyField(blank=True, related_name='target_for_campaigns', to='newsletter.newslettersubscriber'),
        ),
        migrations.AlterField(
            model_name='newsletterimage',
            name='image',
            field=models.ImageField(upload_to='newsletter_images/'),
        ),
    ]
