# Generated by Django 6.0.1 on 2026-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=100, null=True)),
                ('Answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Frequently Asked Question',
            },
        ),
    ]
