# Generated by Django 6.0.1 on 2026-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='visitor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='visitor_name',
            field=models.CharField(max_length=100),
        ),
    ]
